services:
  web:
    container_name: help-web
    build:
      context: .
      dockerfile: ./php.Dockerfile
    restart: always
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor
      - ./session:/var/php/sessions/
    networks:
      - help-network
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        tag: "help-web"
  help-db:
    container_name: help-db
    build:
      context: .
      dockerfile: ./mysql.Dockerfile
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $SQL_ROOT
      MARIADB_DATABASE: help
      MARIADB_USER: $HELPMYSQL_USER
      MYSQL_PASSWORD: $HELPMYSQL_PASSWORD
    ports:
      - "3310:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - help-network
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        tag: "help-db"
  help_myadmin:
    container_name: help-myadmin
    image: phpmyadmin:latest
    restart: "no"
    ports:
      - 8085:80
    environment:
      PMA_HOST: help-db
      UPLOAD_LIMIT: 5000000000
    depends_on:
      - help-db
    networks:
      - help-network
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        tag: "help-myadmin"
networks:
  help-network:
volumes:
  db_data:
  src:
