Ticket $this->ticket_id has been marked as resolved.
<p><strong>Changes Made: </strong></p>
<ul>$this->changesMessage</ul>
<p><strong>Recent Notes:</strong></p>
<ul>$this->notesMessage</ul>
<p>Has your Issue been Resolved? Yes | No.</p>
<p>You have 10 days to re-open this ticket if your issue has not been resolved.</p>
<p><a href="http://localhost:8080/controllers/tickets/edit_ticket.php?id=$this->ticket_id">View ticket $this->$ticket_id</a></p>
