Ticket <?= $this->ticket_id ?> has been resolved
<p><strong>Request Detail:</strong></p>
<div><?= $this->description ?></div>
<?php
if ($this->changes_message) {
    ?>
    <p><strong>Changes Made: </strong></p>
    <ul><?= $this->changes_message ?></ul>
    <?php
}
?>
<p><strong>Recent Notes:</strong></p>
<ul><?= $this->notes_message ?> </ul>
<p>You have 10 days to re-open this ticket if your issue has not been resolved.</p>
<p><a href="<?= $this->site_url ?>/controllers/tickets/edit_ticket.php?id=<?= $this->ticket_id ?>">View ticket <?= $this->ticket_id ?></a></p>