Ticket <?= $this->ticket_id ?> has been updated
<p><strong>Client:</strong> <?= $this->client ?><p>
<p><strong>Location:</strong> <?= $this->location ?><p>
<p><strong>Request Detail:</strong></p>
<div><?= $this->description ?></div>
<p><strong>Recent Notes:</strong></p>
<ul><?= $this->notes_message?> </ul>
<p><a href="<?= $this->site_url ?>/controllers/tickets/edit_ticket.php?id=<?= $this->ticket_id ?>">View ticket <?= $this->ticket_id ?></a></p>