<!DOCTYPE html>
<html>
    <head>
        {% block head %}
            <title>Help For Provo City School District</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="refresh" content="3600">
            <link rel="stylesheet" href="/includes/js/dataTables-1.13.7/jquery.dataTables.min.css">
            <link rel="stylesheet" href="/includes/css/main.css">
            <link rel="icon" type="image/png" href="/includes/img/favicons/favicon-16x16.png" sizes="16x16">
            <link rel="stylesheet" href="/includes/css/jquery-ui.min.css">
            <link rel="stylesheet" type="text/css" href="/includes/css/variables-{{ color_scheme }}.css">
        {% endblock %}
    </head>
    <body>
        <div id="wrapper">
            <header id="mainHeader">
                <a href="/tickets.php">
                    <img id="pcsd-logo" src="/includes/img/pcsd-logo-website-header-160w.png" alt="Provo City School District Logo" />
                </a>
                <nav id="headerNav">
                    <a href="/profile.php">Profile</a>
                    <a href="/tickets.php">Tickets</a>
                    {% if user_permissions.is_supervisor %}
                        <a href="/supervisor.php">Supervisor</a>
                    {% endif %}

                    {% if user_permissions.is_admin %}
                        <a href="/admin.php">Admin</a>
                    {% endif %}

                    <a href="/controllers/logout.php">Logout</a>
                </nav>
                <div id="dayWOHours">
                    Today's WO time: {{ wo_time }} hrs
                </div>
            </header>
            <main id="pageContent">
                {% block content %}

                {% endblock %}
            </main>
            <div id="footer">
                {% block footer %}
                    <p>&copy; 2023 - {{ current_year }} Provo City School District | <a href="https://provo.edu/helpdesk-feedback-form/">Help us Improve our Helpdesk</a></p>
                {% endblock %}
            </div>
        </div>
        <script>
            const userPref = "{{ user_pref }}";
            const ticketLimit = "{{ ticket_limit }}";
        </script>
        <script src="/includes/js/jquery-3.7.1.min.js" type="text/javascript"></script>
        <script src="/includes/js/dataTables-1.13.7/jquery.dataTables.min.js" type="text/javascript"></script>
        <script src="/includes/js/jquery-ui.min.js" type="text/javascript"></script>
        <script src="https://cdn.canvasjs.com/canvasjs.min.js"></script>
        <script src="/vendor/tinymce/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="/includes/js/tinyMCE-conf.js?v=1.0.0" type="text/javascript"></script>
        <script src="/includes/js/dataTables-conf.js?v=1.0.01" type="text/javascript"></script>
        <script src="/includes/js/global.js?v=1" type="text/javascript"></script>
    </body>
</html>